name: ğŸ·ï¸ Deploy VitePress Docs

on:
  push:
    tags:
      - 'v*' # Only trigger when a version tag is pushed, like v1.0.0
  workflow_dispatch:

jobs:
  deploy-vitePress:
    runs-on: ubuntu-latest

    permissions:
      contents: write # Required for GitHub Packages

    steps:
      - name: ğŸ“‚ Checkout code
        uses: actions/checkout@v4

      - name: ğŸ“¦ Set up Node.js and pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: true

      - name: ğŸ“ Build the documentation
        run: pnpm run docs && pnpm run docs:build

      - name: ğŸš€ Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/.vitepress/dist
          branch: docs
          token: ${{ secrets.GITHUB_TOKEN }}
