name: ğŸ·ï¸ Publish and Deploy Documentation

on:
  push:
    tags:
      - 'v*' # Only trigger when a version tag is pushed, like v1.0.0
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write # Required for GitHub Packages
      packages: write # Required for NPM publish

    steps:
      # Step 1: Checkout code
      - name: ğŸ“‚ Checkout code
        uses: actions/checkout@v4

      - name: ğŸ“¦ Set up Node.js for npm
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*' # Use the latest LTS version for stability
          registry-url: 'https://registry.npmjs.org' # Default to npm registry

      - name: ğŸ› ï¸ Install dependencies
        run: npm install --legacy-peer-deps

      # Step 2: Set up pnpm
      - name: ğŸ“¦ Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]

      # Step 3: Lint, format, and test
      - name: ğŸ¨ Lint, format, and test
        run: |
          pnpm run lint:fix
          pnpm run format
          pnpm run test:fast

      # Step 4: Publish to NPM
      - name: ğŸš€ Publish to npm
        run: npm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # Use npm token from secrets

      # Step 5: Set up Node.js for GitHub Packages
      - name: ğŸ¡ Set up Node.js for GitHub Packages
        uses: actions/setup-node@v4
        with:
          registry-url: 'https://npm.pkg.github.com'

      # Step 6: Publish to GitHub Packages
      - name: ğŸ¡ Publish to GitHub Packages
        run: npm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Use GITHUB_TOKEN for GitHub Packages

      # Step 7: Build and deploy documentation
      - name: ğŸ“˜ Build and Deploy Documentation
        run: |
          npm run docs
          npm run docs:clean
          npm run docs:build

      - name: ğŸš€ Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/.vitepress/dist
          branch: docs
          token: ${{ secrets.GITHUB_TOKEN }}
